apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.mcp.port }}
      targetPort: mcp
      protocol: TCP
      name: mcp
  selector:
    {{- include "agent.selectorLabels" . | nindent 4 }}
